// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfagzdjeilevwkeluhha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmYWd6ZGplaWxldndrZWx1aGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NDg5MTQsImV4cCI6MjA1NDIyNDkxNH0.kP7VZym6UcQC3cjiRJkmh3OzIJwy-PBumzNnZBeibU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);